# ~/.config/alacritty/alacritty.toml

[window]
padding.x = 10
padding.y = 10
decorations = "full"
startup_mode = "Maximized"

[font]
size = 16
normal.family = "SFMono Nerd Font Mono"

[colors.primary]
background = "#191724"
foreground = "#e0def4"

[cursor]
style.shape = "Block"
style.blinking = "On"

[scrolling]
history = 5000
multiplier = 3

