# ~/.config/alacritty/alacritty.toml

[window]
padding.x = 10
padding.y = 10
decorations = "None"
startup_mode = "Maximized"
option_as_alt = "Both"

[font]
size = 18
normal.family = "JetBrainsMono Nerd Font"

[colors.primary]
background = "#191724"
foreground = "#e0def4"

[cursor]
style.shape = "Block"
style.blinking = "On"

[scrolling]
history = 5000
multiplier = 3

[[keyboard.bindings]]
key = "Left"
mods = "Alt"
chars = "\u001bb"

[[keyboard.bindings]]
key = "Right"
mods = "Alt"
chars = "\u001bf"
